//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token not found.
        /// </summary>
        public static string AccessTokenNotFound {
            get {
                return ResourceManager.GetString("AccessTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code {0} from Instagram API: {1}.
        /// </summary>
        public static string BadRequestToInstagram {
            get {
                return ResourceManager.GetString("BadRequestToInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BigCustomError {
            get {
                return ResourceManager.GetString("BigCustomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create team link.
        /// </summary>
        public static string CanNotCreate {
            get {
                return ResourceManager.GetString("CanNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims doesn&apos;t exist.
        /// </summary>
        public static string ClaimsNotExist {
            get {
                return ResourceManager.GetString("ClaimsNotExist", resourceCulture);
            }
        ///   Looks up a localized string similar to Cannot map entity.
        /// </summary>
        public static string CanNotMap {
            get {
                return ResourceManager.GetString("CanNotMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text was not parsed successfully.
        /// </summary>
        public static string CanNotParseText {
            get {
                return ResourceManager.GetString("CanNotParseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this email is already registered.
        /// </summary>
        public static string EmailIsUse {
            get {
                return ResourceManager.GetString("EmailIsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram settings are not configured properly..
        /// </summary>
        public static string EmptyInstagramSettings {
            get {
                return ResourceManager.GetString("EmptyInstagramSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment settings are not configured properly.
        /// </summary>
        public static string EmptyPaymentSettings {
            get {
                return ResourceManager.GetString("EmptyPaymentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search query cannot be null or empty.
        /// </summary>
        public static string EmptyQuery {
            get {
                return ResourceManager.GetString("EmptyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any {0}.
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any {0} by a streetcode id: {1}.
        /// </summary>
        public static string EntityNotFoundWithStreetcode {
            get {
                return ResourceManager.GetString("EntityNotFoundWithStreetcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any tag by the title: {1}.
        /// </summary>
        public static string EntityNotFoundWithTitle {
            get {
                return ResourceManager.GetString("EntityNotFoundWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} by entered Url - {url}.
        /// </summary>
        public static string EntityNotFoundWithUrl {
            get {
                return ResourceManager.GetString("EntityNotFoundWithUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any {0} with corresponding id: {1}.
        /// </summary>
        public static string EntityWithIdNotFound {
            get {
                return ResourceManager.GetString("EntityWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a {0} by a streetcode id: {1}, because such streetcode doesn`t exist.
        /// </summary>
        public static string EntityWithStreetcodeNotFound {
            get {
                return ResourceManager.GetString("EntityWithStreetcodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any streetcode with corresponding tagid: {1}.
        /// </summary>
        public static string EntityWithStreetcodeTagNotFound {
            get {
                return ResourceManager.GetString("EntityWithStreetcodeTagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact with id not found in list of new position.
        /// </summary>
        public static string FactNotFoundInListPosition {
            get {
                return ResourceManager.GetString("FactNotFoundInListPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add role.
        /// </summary>
        public static string FailAddRole {
            get {
                return ResourceManager.GetString("FailAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create user.
        /// </summary>
        public static string FailCreateUser {
            get {
                return ResourceManager.GetString("FailCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set Token to the Black List!.
        /// </summary>
        public static string FailedToSetTokenInBlackList {
            get {
                return ResourceManager.GetString("FailedToSetTokenInBlackList", resourceCulture);
            }
        ///   Looks up a localized string similar to Failed to save changes to the database..
        /// </summary>
        public static string FailSaveChangesDB {
            get {
                return ResourceManager.GetString("FailSaveChangesDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email message.
        /// </summary>
        public static string FailSendEmail {
            get {
                return ResourceManager.GetString("FailSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to {0}.
        /// </summary>
        public static string FailToConvertNull {
            get {
                return ResourceManager.GetString("FailToConvertNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a {0}.
        /// </summary>
        public static string FailToCreateA {
            get {
                return ResourceManager.GetString("FailToCreateA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create an {0}.
        /// </summary>
        public static string FailToCreateAn {
            get {
                return ResourceManager.GetString("FailToCreateAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete a {0}.
        /// </summary>
        public static string FailToDeleteA {
            get {
                return ResourceManager.GetString("FailToDeleteA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete an {0}.
        /// </summary>
        public static string FailToDeleteAn {
            get {
                return ResourceManager.GetString("FailToDeleteAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot map streetcode to shortDTO.
        /// </summary>
        public static string FailToMap {
            get {
                return ResourceManager.GetString("FailToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text was not parsed successfully.
        /// </summary>
        public static string FailToParse {
            get {
                return ResourceManager.GetString("FailToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update a {0}.
        /// </summary>
        public static string FailToUpdate {
            get {
                return ResourceManager.GetString("FailToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount and page must be greater than zero.
        /// </summary>
        public static string InvalidPaginationParameters {
            get {
                return ResourceManager.GetString("InvalidPaginationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this login is already registered.
        /// </summary>
        public static string LoginIsUse {
            get {
                return ResourceManager.GetString("LoginIsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoCustomError {
            get {
                return ResourceManager.GetString("NoCustomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token not found.
        /// </summary>
        public static string RefreshTokenNotFound {
            get {
                return ResourceManager.GetString("RefreshTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles not found.
        /// </summary>
        public static string RolesNotFound {
            get {
                return ResourceManager.GetString("RolesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add records because such streetcode already exists.
        /// </summary>
        public static string StreetcodeAlreadyExist {
            get {
                return ResourceManager.GetString("StreetcodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any streetcode with corresponding index: {1}.
        /// </summary>
        public static string StreetcodeIndexNotFound {
            get {
                return ResourceManager.GetString("StreetcodeIndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The streetcode content is null.
        /// </summary>
        public static string StreetCodeIsNull {
            get {
                return ResourceManager.GetString("StreetCodeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No streetcodes exist now.
        /// </summary>
        public static string StreetcodeNotExist {
            get {
                return ResourceManager.GetString("StreetcodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find streetcode by transliteration url: {1}.
        /// </summary>
        public static string StreetcodeUrlNotFound {
            get {
                return ResourceManager.GetString("StreetcodeUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add word because such term already exists.
        /// </summary>
        public static string TermAlreadyExist {
            get {
                return ResourceManager.GetString("TermAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline item title is null or empty.
        /// </summary>
        public static string TitleNullEmpty {
            get {
                return ResourceManager.GetString("TitleNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find streetcode by transliteration url: {1}.
        /// </summary>
        public static string ExpiredToken
        {
            get
            {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Cannot find streetcode by transliteration url: {1}.
        /// </summary>
        public static string ClaimsNotExist
        {
            get
            {
                return ResourceManager.GetString("ClaimsNotExist", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Cannot find streetcode by transliteration url: {1}.
        /// </summary>
        public static string AccessTokenNotFound
        {
            get
            {
                return ResourceManager.GetString("AccessTokenNotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Cannot find streetcode by transliteration url: {1}.
        /// </summary>
        public static string RefreshTokenNotFound
        {
            get
            {
                return ResourceManager.GetString("RefreshTokenNotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Fail to Update user.
        /// </summary>
        public static string UserUpdateFailed {
            get {
                return ResourceManager.GetString("UserUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id {0} not found.
        /// </summary>
        public static string UserWithIdNotFound {
            get {
                return ResourceManager.GetString("UserWithIdNotFound", resourceCulture);
            }
        }
    }
}
